FROM node:alpine

WORKDIR '/app'

COPY package.json .

# for corporate firewall to avoid ssl certificate
RUN npm config set registry "http://registry.npmjs.org"

RUN npm install

COPY . .

CMD ["npm", "run", "start"]

